### ISSUE TITLE
Bot failing to start

### ISSUE THREAD

**Issue by rasodu** [GainsNetwork/nft-bot-v3#1]
I am getting below error:
```
eb 14 19:40:37 gainsfarmnftbot bash[2316815]: Welcome to the gTrade NFT bot!
Feb 14 19:40:37 gainsfarmnftbot bash[2316815]: Listening on port 4002
Feb 14 19:40:37 gainsfarmnftbot bash[2316815]: WSS wss://matic-mainnet-full-ws.bwarelabs.com error
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: Connected to WSS wss://rpc-mainnet.matic.quiknode.pro.
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: Switched to WSS wss://rpc-mainnet.matic.quiknode.pro
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: wss://matic-mainnet-full-ws.bwarelabs.com closed: trying to reconnect...
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: WSS wss://matic-mainnet-full-ws.bwarelabs.com error
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: /home/vagrant/myprojects/nft-bot-v3/node_modules/web3-core-helpers/lib/errors.js:28
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:         var err = new Error('Returned error: ' + message);
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:                   ^
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: Error: Returned error: execution reverted
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at Object.ErrorResponse (/home/vagrant/myprojects/nft-bot-v3/node_modules/web3-core-helpers/lib/err>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at Object.callback (/home/vagrant/myprojects/nft-bot-v3/node_modules/web3-core-requestmanager/lib/i>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at /home/vagrant/myprojects/nft-bot-v3/node_modules/web3-providers-ws/lib/index.js:114:45
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at Array.forEach (<anonymous>)
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at WebsocketProvider._onMessage (/home/vagrant/myprojects/nft-bot-v3/node_modules/web3-providers-ws>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/vagrant/myprojects/nft-bot-v3/node_modules>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at W3CWebSocket.onMessage (/home/vagrant/myprojects/nft-bot-v3/node_modules/websocket/lib/W3CWebSoc>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at WebSocketConnection.<anonymous> (/home/vagrant/myprojects/nft-bot-v3/node_modules/websocket/lib/>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at WebSocketConnection.emit (node:events:390:28)
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at WebSocketConnection.processFrame (/home/vagrant/myprojects/nft-bot-v3/node_modules/websocket/lib>
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at /home/vagrant/myprojects/nft-bot-v3/node_modules/websocket/lib/WebSocketConnection.js:323:40
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]:   data: null
Feb 14 19:40:38 gainsfarmnftbot bash[2316815]: }
```

**Comment by Dopaminergics** [comment]
Please try using a new RPC. 
https://polygon-rpc.com/ 
https://rpc-mainnet.matic.network 
https://matic-mainnet.chainstacklabs.com 
https://rpc-mainnet.maticvigil.com 
https://rpc-mainnet.matic.quiknode.pro 
https://matic-mainnet-full-rpc.bwarelabs.com

Or sign up for a personal RPC endpoint somewhere like chainstack =)

**Comment by GainsNetwork** [comment]
The v3 bot is meant to be used once v6 is live, which will be in about 3.5 hours from now, before then the v2 bot has to be used.
